Tests: Remove-member
d-iii-s/teachers-gitlab pull request #6
Opened 2024-08-04 14:03 UTC by otulach

2024-08-05 04:49 UTC, vhotspur requested changes
Looks good, but I would like to ask you to squash the two commits to get rid of the history with visible avatar URLs etc. of real users. Thanks!

2024-08-05 04:49 UTC, vhotspur commented on tests/test_rmmember.py
> +    [
Would you, please, reformat this by indenting (and possibly keeping the `[` on previous line)?

```
def test_remove_member(mock_gitlab):
    ...
    mock_gitlab.register_project(42, 'student/alpha', members=[
        {
            ...
        },
        {
            ...
        },
    ])
```

Thanks!

2024-08-20 14:52 UTC, otulach commented
Reformated and rebased. :)

2024-08-20 15:25 UTC, vhotspur requested changes

2024-08-20 21:01 UTC, otulach commented on tests/test_rmmember.py
> +        1,
I am not sure what should login column represent. Whether it's just the name of the column, or something else.
Do you have an idea?

2024-08-21 06:47 UTC, vhotspur commented on tests/test_rmmember.py
> +        1,
It is the name of the column where the member login is specified (i.e. so that we know which user to actually remove). Here, it will be `login`.

2024-08-21 06:49 UTC, vhotspur commented
I think you still miss the _report unknown_ directive, hence the test is still passing even if it does not test anything (I wonder if we can check automatically for this somehow).

2024-08-21 07:25 UTC, vhotspur commented
> [...] I wonder if we can check automatically for this somehow

It was actually easier than I have originally thought :-).

The update that fails the test if the `report_unknown()` is not called is already in `master`.

2024-08-21 14:54 UTC, otulach commented
I also added the test for an actual member, request DELETE however wasn't needed. Is there anything I overlooked?

2024-08-21 19:03 UTC, vhotspur commented
> I also added the test for an actual member, request DELETE however wasn't needed. Is there anything I overlooked?

It seems to me that even in the second test the member is reported as 404?

2024-08-22 09:39 UTC, otulach commented
Oh, yes that should certainly be the case. Thanks a lot!

2024-09-09 14:02 UTC, merged